name: Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Show variables
        run: |
          echo "GITHUB_ACTION=${GITHUB_ACTION}"
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT}"
          echo "GITHUB_RUN_ID=${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"
          echo "GITHUB_RUN_ID=${GITHUB_RUN_ID}"

      - name: Show git diff
        run: |
          git diff --name-status ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF}
