name: Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show variables
        run: |
          echo "GITHUB_ACTION=${GITHUB_ACTION}"
          echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT}"
          echo "GITHUB_RUN_ID=${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"
          echo "GITHUB_SHA=${GITHUB_SHA}"

      - name: Show git diff
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }}  |  xargs -L1 echo >> output
          while read line; do
            if [[ "${line:0:1}" == "M" ]] && [[ ! "$(echo "$line" | cut -d " " -f 2)" =~ ".github" ]]; then
              echo "Modified Status on $(echo "$line" | cut -d " " -f 2)"
              echo $(echo "$line" | cut -d " " -f 2) >> write_list
            elif [[ "${line:0:1}" == "A" ]] && [[ ! "$(echo "$line" | cut -d " " -f 2)" =~ ".github" ]]; then
              echo "Added Status on $(echo "$line" | cut -d " " -f 2)"
              echo $(echo "$line" | cut -d " " -f 2) >> write_list
            elif [[ "${line:0:1}" == "D" ]] && [[ ! "$(echo "$line" | cut -d " " -f 2)" =~ ".github" ]]; then
              echo "Deleted Status on $(echo "$line" | cut -d " " -f 2)"
              echo $(echo "$line" | cut -d " " -f 2) >> delete_list
            fi
          done < output
          printf "Write List\n"
          cat write_list || echo "No files to write"
          printf "\n\nDelete List\n"
          cat delete_list || echo "No files to delete"