name: Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  deploy:
    name: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: ${{ env.GITHUB_REF_NAME }}
